# Generated by Django 4.2.1 on 2023-07-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regmodel',
            name='image',
            field=models.FileField(upload_to='bank_app/static'),
        ),
    ]
