# Generated by Django 4.2.1 on 2023-07-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_alter_regmodel_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmodel',
            name='ac_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regmodel',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
