# Generated by Django 4.2.1 on 2023-07-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_delete_withdraw_regmodel_withdraw_amt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regmodel',
            old_name='withdraw_amt',
            new_name='withdrawamt',
        ),
    ]
