from django.urls import path
from .views import *
urlpatterns=[
    path('register/',registration),
    path('login/',login),
    path('profile/',profile),
    path('editdet/<int:id>',editdet),
    path('editimg/<int:id>',edimage),
    path('addamount/<int:id>',addmoney),
    path('success/',success),
    path('debit/<int:id>',withdrawmoney),
    path('checkbal/<int:id>',checkbalance),
    path('baldis/',balancedisplay),
    path('debit/',debit),
    path('minist/<int:id>',ministatement),
    path('depst/',depmini),
    path('withst/',withmini),
    path('news/',news),
    path('newsdis/',newsdisplay),
    path('newsdisadmin/',newsdisadmin),
    path('newsedit/<int:id>',newsedit),
    path('newsdelete/<int:id>',deletenews),
    path('adminlog/',loginadmin),
    path('admindis/',admindis),
    path('wishlist/<int:id>',wish),
    path('wishpg/',wishlistpg),
    path('remove/<int:id>',wishremove),
    path('logout/',logout_view),
    path('forgot/',forgot_password),
    path('change/<int:id>',change_password),

    path('table/',tablesearch),
    path('trans/<int:id>',cashsendingview),
    path('sendsuccess/',sendsuccess),
]